
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhabpjhqjubuyznngqpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYWJwamhxanVidXl6bm5ncXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NDA2MzksImV4cCI6MjA4MzMxNjYzOX0.9XZ1TB8T2cKWPJCfsbiRjmeJ2mWKy2v8xZ54yeakuBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
