/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmbtrengine_free: (a: number, b: number) => void;
export const __wbg_wasmbtrtransferctx_free: (a: number, b: number) => void;
export const __wbg_wasmsendsession_free: (a: number, b: number) => void;
export const computeSas: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const generateEphemeralKeyPair: () => [number, number, number];
export const generateIdentityKeyPair: () => [number, number, number];
export const generateSecurePeerCode: () => [number, number];
export const isValidPeerCode: (a: number, b: number) => number;
export const negotiateBtr: (a: number, b: number, c: number) => [number, number];
export const openBoxPayload: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const sealBoxPayload: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const sha256Hex: (a: number, b: number) => [number, number];
export const wasmbtrengine_beginTransferReceive: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const wasmbtrengine_beginTransferSend: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmbtrengine_cleanupDisconnect: (a: number) => void;
export const wasmbtrengine_endTransfer: (a: number) => void;
export const wasmbtrengine_new: (a: number, b: number) => [number, number, number];
export const wasmbtrengine_ratchetGeneration: (a: number) => number;
export const wasmbtrtransferctx_chainIndex: (a: number) => number;
export const wasmbtrtransferctx_cleanupCancel: (a: number) => void;
export const wasmbtrtransferctx_cleanupComplete: (a: number) => void;
export const wasmbtrtransferctx_generation: (a: number) => number;
export const wasmbtrtransferctx_localRatchetPub: (a: number) => [number, number];
export const wasmbtrtransferctx_openChunk: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmbtrtransferctx_sealChunk: (a: number, b: number, c: number) => [number, number, number];
export const wasmbtrtransferctx_transferId: (a: number) => [number, number];
export const wasmsendsession_beginSend: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const wasmsendsession_finish: (a: number) => [number, number, number, number];
export const wasmsendsession_isSendActive: (a: number) => number;
export const wasmsendsession_new: () => number;
export const wasmsendsession_nextChunk: (a: number) => [number, number, number];
export const wasmsendsession_onAccept: (a: number, b: number, c: number) => [number, number];
export const wasmsendsession_onCancel: (a: number, b: number, c: number) => [number, number];
export const wasmsendsession_onPause: (a: number, b: number, c: number) => [number, number];
export const wasmsendsession_onResume: (a: number, b: number, c: number) => [number, number];
export const wasmsendsession_state: (a: number) => [number, number];
export const init: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
